export const FETCH_MOVIE_SHOWING = "FETCH_MOVIE_SHOWING";
export const FETCH_MOVIE_UPCOMING = "FETCH_MOVIE_UPCOMING";
export const FETCH_MOVIE_DETAIL = "FETCH_MOVIE_DETAIL";
export const FETCH_CREDENTAIL = "FETCH_CREDENTAIL";
