export const MOVIE_LIST_REQUEST = "MOVIE_LIST_REQUEST";
export const GET_MOVIE_LIST_SUCCESS = "GET_MOVIE_LIST_SUCCESS";
export const GET_MOVIE_LIST_FAILED = "GET_MOVIE_LIST_FAILED";
export const GET_MOVIE_DETAIL_SUCCESS = "GET_MOVIE_DETAIL_SUCCESS";
export const GET_MOVIE_DETAIL_FAILED = "GET_MOVIE_DETAIL_FAILED";
export const GET_THEATERLIST_SUCCESS = "GET_THEATERLIST_SUCCESS";
export const GET_THEATERLIST_FAILED = "GET_THEATERLIST_FAILED";

// THEM
export const GET_SCHEDULE_THEATER_SYSTEM_SUCCESS =
  "GET_SCHEDULE_THEATER_SYSTEM_SUCCESS";

export const GET_SCHEDULE_THEATER_SYSTEM_FAILED =
  "GET_SCHEDULE_THEATER_SYSTEM_FAILED";

export const FETCH_CREDENTAIL = "FETCH_CREDENTAIL";
